---

name: ci
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: ^1.15

    - name: Test tree package
      run: |
        cd tree
        go mod download
        go test -count=1 -cover -v
        cd -

    - name: Test extendedTree package
      run: |
        cd extendedTree
        go mod download
        go test -count=1 -cover -v
        cd -
